export { default as CompletedPreviewComics } from './CompletedPreviewComics'
export { default as RecentUpdateComics } from './RecentUpdateComics'
export { default as RecommendComics } from './RecommendComics'
export { default as SlidePreviewComics } from './SlidePreviewComics'
export { default as TopPreviewComics } from './TopPreviewComics'
