export { default as Home } from './Home'
export { default as ComicsList } from './ComicsList'
export { default as ComicsGenre } from './ComicsGenre'
export { default as ComicsDetail } from './ComicsDetail'
export { default as ComicsChapter } from './ComicsChapter'
export { default as ComicsSearch } from './ComicsSearch'
export { default as Download } from './Download'
